version: "3.9"
services:
  db:
    image: postgres:15.2-alpine
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=GOBO
      - POSTGRES_DB=GOBO

  api:
    image: gobo/api
    build:
      context: .
      dockerfile: api/Dockerfile.aws
    command: "gunicorn main:app --preload -b 0.0.0.0:5000 --log-level info"
    ports:
      - 4242:5000

  worker:
    image: gobo/worker
    build:
      context: .
      dockerfile: worker/Dockerfile.aws
