version: "3.9"
services:
  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=GOBO
      - POSTGRES_DB=GOBO

  api:
    image: gobo/api
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db
    ports:
      - 4242:5000
    volumes:
      - ./api:/usr/src/app
      - ./db:/usr/src/app/db
      - ./joy:/usr/src/app/joy
      - ./models:/usr/src/app/models
      - ./tasks:/usr/src/app/tasks
      - ./clients:/usr/src/app/clients
      - ./draft_files:/usr/src/app/draft_files

  worker:
    image: gobo/worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    deploy:
      mode: replicated
      replicas: 7
    depends_on:
      - db
    volumes:
      - ./worker:/usr/src/app
      - ./db:/usr/src/app/db
      - ./joy:/usr/src/app/joy
      - ./models:/usr/src/app/models
      - ./tasks:/usr/src/app/tasks
      - ./clients:/usr/src/app/clients
      - ./draft_files:/usr/src/app/draft_files