version: "3.9"
services:
  db:
    image: postgres:15.2-alpine
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=GOBO
      - POSTGRES_DB=GOBO

  api:
    image: gobo/api
    build:
      context: .
      dockerfile: api/Dockerfile
    command: "gunicorn main:app -b 0.0.0.0:5000 --log-level info"
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./api:/usr/src/app
      - ./db:/usr/src/app/db
      - ./joy:/usr/src/app/joy
      - ./models:/usr/src/app/models
      - ./clients:/usr/src/app/clients

  worker:
    image: gobo/worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - db
    volumes:
      - ./worker:/usr/src/app
      - ./db:/usr/src/app/db
      - ./joy:/usr/src/app/joy
      - ./models:/usr/src/app/models
      - ./clients:/usr/src/app/clients